sudo: required

before_install:
  - ls
  - cd AmeyaWagh/Hipsters_In_Swarm
  - bash ./install.sh

language: cpp

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make